SPEAKER_MAP = {'Announcer':'Announcer', 'Howard_Kurtz':'Howard', 'Frank_Sesno':'Frank', 'Arianna_Huffington':'Arianna',
       'Lucy_Dalglish':'Lucy', '_Bill_Schneider':'Schneider', "Bill_O'Reilly":"O'Reilly",
       'Jeff_Greenfield':'Jeff', 'speaker2':'B', 'speaker1':'A', 'President_Bush':'Bush',
       'Louis_Freeh':'Louis', 'Lanny_Davis':'Lanny', 'speaker3':'C', 'Tom_Friedman':'Tom',
       'speaker4':'D', 'Bob_Schieffer':'Bob', 'Anderson_Cooper':'Anderson', 'Alan_Colmes':'Alan',
       'Keith_Olbermann':'Keith', 'Michelle_Kosinski':'Michelle', 'Wolf_Blitzer':'Wolf', 'speaker5':'E',
       'speaker#1':'AA', 'Xu_li':'Xu', 'Wang_shilin':'Wang', 'Zhou_hanhua':'Zhou', 'Yang_yang':'Yang',
       'Zhou_hanhua,Wang_shilin,Zhou_hanhua':'three', 'speaker#2':'BB', 'speaker#3':'CC',
       'speaker#4':'DD', 'Meng_xianlong':'Meng', 'Yang_yang,Wang_shilin':'two',
       'Wang_shilin,Yang_yang':'two', 'speaker#5':'EE', 'speaker_1':'MSNBC#1', 'speaker_2':'MSNBC#2',
       'speaker_3':'MSNBC#3', 'speaker_4':'MSNBC#4', 'Tim_Russert':'Tim', 'Nicholas_Burns':'Nicholas',
       'Governor_Richardson':'Richardson', 'Robert_Gallucci':'Robert', 'Ashton_Carter':'Ashton',
       'Madeline_Albright':'Albright', 'Bill_Clinton':'Clinton', 'Speaker_5':'MSNBC#5', 'President_Ford':'Ford',
       '-':'-', 'Ye_jingzhong':'Ye', 'Jiang_beiwen':'Jiang', '_بو_ثاري_':'Bu', '_متعاون_':'Collaborator',
       '_فوق_الشمس_':'Sun', '_الهاوي_':'Amateur', '_قيس_ابن_ابيه_':'Qais', '_الاماراتى_':'UAE',
       '_منبع_الكلمة_':'Source', '_ولد_الباطن_':'Born', '_ابو_بكر_الرازي_':'Abu',
       '_رئيس_النادي_':'President', '_الوهج_':'Glow', '_فريدمن_نوعه_':'Unique', '_ابو_جوري_':'Abo',
       '_ســالــم_':'Salem', '_Jeff_':'Jeff', '_Anonymous_':'Anonymous', '_Sepka_the_Space_Weasel_':'Sepka',
       '_ericswan_':'Eric', '_jon_':'Jon', '_starroute_':'Starroute', '_Richard_':'Richard', '_DaftAida_':'Daft',
       '_Nate_':'Nate', '_Folly_':'Folly', '_Cadmus_':'Cadmus', '_foist_lastus_':'Foist', '_Tronicus_':'Tronicus',
       '_Hilda_Martinez_':'Hilda', '_Lone_Ranger_':'Lone', '_Avalon_':'Avalon', '_Max_Lichtor_':'Max',
       '_TheTruthIsOutThere_':'Truth', '_Mickey_':'Mickey', '_Kiba_':'Kiba', '_613305_':'613305',
       '_mikecat_':'mikecat', '_poqi_':'poqi', '_Dift_Wu_':'Dift', '_郭凯经济笔记_':'Guo', '_darling0823_':'darling0823',
       'Matthew':'Matthew', 'Acts':'Acts', 'Revelation':'Revelation', '1_Corinthians':'Corinthians', '2_Corinthians':'Corinthians',
       'Luke':'Luke', 'Mark':'Mark', 'Romans':'Romans', 'John':'John', 'Hebrews':'Hebrews', 'B':'B', 'A':'A'}
